# Site settings
name: Pushpak Narasimhan
title: Pushpak Narasimhan | iOS Developer
description: iOS developer focused on building beautiful apps
url: https://pushpaknarasimhan.github.io/
baseurl: ''
email: pushpak.narasimhan@gmail.com
#cover: https://bchiang7.github.io/img/og.png
logo: https://pushpaknarasimhan.github.io/img/emojis/technologist.png
resume: https://pushpaknarasimhan.github.io/resume.pdf
social:
  - title: email
    url: mailto:pushpak.narasimhan@gmail.com
  - title: twitter
    url: https://twitter.com/_PushpakN
  - title: instagram
    url: https://instagram.com/pushpak.narasimhan/
  - title: github
    url: https://github.com/pushpaknarasimhan
  - title: linkedin
    url: https://www.linkedin.com/in/pushpakn/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
